# Generated by Django 4.0.3 on 2022-03-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
